### ISSUE TITLE
Bug: Notifications get reversed

### ISSUE THREAD

**Issue by ChrisLaganiere** [uclaradio/uclaradio-iOS#10]
Notifications are getting corrupted so that they arrive 15 or 30 minutes *after* a show begins...

<img src="https://cloud.githubusercontent.com/assets/2042745/23007404/4f51f08e-f3bd-11e6-97c3-0583dc3e1957.PNG" width=400>

Notice how the notification for this show came 15 minutes after it started, at 11:15

**Comment by nathunsmitty** [comment]
Any advice on how to duplicate? I haven't experienced this at all on my phone.

**Comment by ChrisLaganiere** [comment]
I can't say how exactly but shows get converted somehow, so they get reversed like this one-by-one.

My assumption in that case is that it's converting them to strings for `UserDefaults` and back...
