### ISSUE TITLE
Compatible Xcode 7.3

### ISSUE THREAD

**Issue by Elicast** [uclaradio/uclaradio-iOS#19]
This app requires Sdk 9.1?
Wanted to know if it is compatible with xcode 7.3?
When i was testing the code it displayed several errors

Tanks

**Comment by nathunsmitty** [comment]
The app currently supports 9.3 or later. It works fine on the latest version of Xcode (8.3.2 as of when I'm writing this). Make sure you run `pod install` and open the `UCLA Radio.xcworkspace` in Xcode; we use [Cocoapods](https://cocoapods.org) to manage dependencies.
