### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by ChrisLaganiere** [uclaradio/uclaradio-iOS#2]
Users should be able to register for notifications when a show they like is coming up!

We should be able to clear this notification programmatically via the API when the show is no longer running (over break)

**Comment by nathunsmitty** [comment]
What would the API send in order for the app to know to clear a notification?

**Comment by ChrisLaganiere** [comment]
How about if we use the local cached copy of the show schedule to make sure a show with the same id is still publicly listed before displaying a notification for that show? If we do that and have a list somewhere for the user to see / remove shows they're subscribed to, then we can handle all the cases nicely:

1. Show is public and user wants notifications -> show notification! 🎉 
2. Show is still going, but not public this week and user wants notification -> no notification this week, but will try again next week 🌵 
3. Show is not public and user doesn't want notifications anymore -> they can go into the global list and remove it, even if the show page isn't available in schedule 🔥 
4. Show is public and user doesn't want notifications -> they just deselect the switch on the show page! 😢

**Comment by nathunsmitty** [comment]
I'm a bit confused by the public/not public show thing. Is this a feature currently implemented or is this something I should add? Also, is it intended more for like one-off when a DJ misses their show one week so we shouldn't show a notification or rather making all shows private and and not sending any notifications over a break?

**Comment by ChrisLaganiere** [comment]
Public / no public is implemented - if a show isn't public, you won't get it from `/api/schedule`.. That would be for both cases, dj doesn't show up or the show is off of the air for a few weeks.

**Comment by nathunsmitty** [comment]
Okay, so I've been thinking a lot about how we want to implement a "Notifications" screen that allows users to manage all their notifications in one place. The 2 most logical places I could think of that would segue to this notifications scene would be either the about screen or the shows screen. 

I also wasn't sure what icon would work best; I played around with both a settings gear and a notification bell. Let me know which one you think would be best, or if you want to do something different from the options here.

**Shows Screen**
_With gear:_
![schedule w gear](https://cloud.githubusercontent.com/assets/5677971/20998987/568424f4-bcc6-11e6-9625-92c38c87c092.png)
_With bell:_
![schedule w bell](https://cloud.githubusercontent.com/assets/5677971/20999019/93f0cc34-bcc6-11e6-801a-8f55096ebe16.png)

**Comment by nathunsmitty** [comment]
**About Screen**
_With gear:_
![about w gear](https://cloud.githubusercontent.com/assets/5677971/20999038/be079b42-bcc6-11e6-9f4b-5efd12cf752c.png)
_With bell:_
![about w bell](https://cloud.githubusercontent.com/assets/5677971/20999099/376341d0-bcc7-11e6-8a1a-a1f107f84df0.png)

**Comment by nathunsmitty** [comment]
I've also been thinking about what the actual notifications screen would best look like. I feel like what would be best would be a UITableView-esque screen similar to the shows page. Here's a little mockup of what I imagined:
![notification screen](https://cloud.githubusercontent.com/assets/5677971/20999253/29a0c634-bcc8-11e6-90b5-2ae0d9519630.png)
And deleting a notification would just be a swipe left:
![notification screen delete](https://cloud.githubusercontent.com/assets/5677971/20999265/394bd358-bcc8-11e6-8af5-000dd0589cc0.png)
Users would also have a couple options in terms of deciding when their notifications happen and would be able to fine-tune these settings by clicking on a cell, which would then segue to the settings for a particular show:
![notification details screen](https://cloud.githubusercontent.com/assets/5677971/20999302/7b32ace2-bcc8-11e6-9d3d-1587085a581d.png)

Thoughts?

**Comment by ChrisLaganiere** [comment]
Looks awesome @nathunsmitty ! I like the bell icon. A tableview is a good idea - the swipe to remove won't work quite like that but we can play with it. The multi select interface is good, we could also do a switch with a scroll option for how many minutes before 👍

**Comment by ChrisLaganiere** [comment]
@nathunsmitty you can close this issue 👍
