### ISSUE TITLE
Remove last playing bar

### ISSUE THREAD

**Issue by nathunsmitty** [uclaradio/uclaradio-iOS#24]

**Comment by haejinjo** [comment]
I'm kinda confused. Didn't this get closed? I re-downloaded the app and the last playing bar is still there. Brian's DJ bios aren't there either.

**Comment by nathunsmitty** [comment]
Yeah... so the app needs to be updated. I think I kinda messed some stuff up by putting the `pods/` folder in `.gitignore` though if either you or @bsakhuja wants to fix that and upgrade it to Swift 4 we could roll it out then!

**Comment by binerys** [comment]
Fixed by #33 and #26
